name: Test
on: [push, pull_request]

jobs:
  setup:
    strategy:
      matrix:
        # Keep the matrix for when jdk 17 rc come out
        java: [ 17 ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-java@v2
          with:
            distribution: "temurin"
            java-version: ${{ matrix.java }}
      - uses: actions/checkout@v2
  check:
    runs-on: ubuntu-20.04
    needs:
      - setup
    steps:
      - run: ./gradlew check --stacktrace --parallel
  build:
    runs-on: ubuntu-20.04
    needs:
      - check
    steps:
      - run: ./gradlew build --stacktrace --parallel
  publish:
    runs-on: ubuntu-20.04
    needs:
      - build
    steps:
      - run: ./gradlew publish --stacktrace --parallel
        env:
          SNAPSHOTS_URL: ${{ secrets.SNAPSHOTS_URL }}
          SNAPSHOTS_USERNAME: ${{ secrets.SNAPSHOTS_USERNAME }}
          SNAPSHOTS_PASSWORD: ${{ secrets.SNAPSHOTS_PASSWORD }}
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./*/build/libs/
  test:
    runs-on: ubuntu-20.04
    needs:
      - build
    steps:
      - run: mkdir run && echo "eula=true" >> run/eula.txt
      - run: ./gradlew :runAutoTestServer --stacktrace
