name: Test
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java: [17, 19]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - name: Check Licenses and Generate QMJs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkLicenses generateQmj --parallel --stacktrace
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build publishToMavenLocal --stacktrace --parallel -Porg.gradle.parallel.threads=4
      - uses: actions/upload-artifact@v3
        with:
          name: Production Mods
          path: |
            ./**/build/libs/
            !./build-logic/**
            !./**/build/libs/*-javadoc.jar
            !./**/build/libs/*-sources.jar
            !./**/build/libs/*-testmod.jar
      - uses: actions/upload-artifact@v3
        with:
          name: Test Mods
          path: ./**/build/libs/*-testmod.jar
      - run: zip -r qsl.zip ./*
      - uses: actions/upload-artifact@v3
        with:
          name: QSL project ${{ matrix.java }}
          path: ./qsl.zip
          retention-days: 1
  run_test_server:
    strategy:
      matrix:
        java: [17, 19]
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - uses: actions/download-artifact@v3
        with:
          name: QSL project ${{ matrix.java }}
      - run: unzip "QSL project ${{ matrix.java }}.zip"
      - run: rm "QSL project ${{ matrix.java }}.zip" && unzip qsl.zip
      - run: mkdir run && echo "eula=true" >> run/eula.txt
      - name: Run auto-test server
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :runAutoAllTestServer --stacktrace
